package com.reds.service.cassandraloaderapi;

import com.reds.service.cassandraloaderapi.info.CassandraloaderInfo;
import com.reds.generator.redsannotations.Service;
import java.util.List;
import com.reds.service.cassandraloaderapi.exception.*;

/**
 * <b>Purpose:</b> Service Interface class for Cassandraloader.
 *
 * @author <b>Algols Builder</b>
 *
 * This code is generated by Reds on 30/07/2020 02:11:30
 */
@Service(type = "BUSINESS", name = "Cassandraloader", root = "sfmigration")
public interface Cassandraloader {

    public CassandraloaderInfo getInfo();
}
