package com.reds.service.cassandraloaderapi.exception;

 /**
 * <b>Purpose:</b> ErrorCodes class for Cassandraloader
 * 
 * @author <b>Algols Builder</b>
 *
 *     This code is generated by Reds
 */
public class CassandraloaderErrorCodes {
	public static String errorCode(int id) {
		switch (id) {
		case 1:
			return "001";
		case 9:
			/*ERROR Code Related to Data Management*/
			return "009";
		case 10:
			/*ERROR Code Related to Web Server*/
			return "010";
		case 11:
			/*ERROR Code Related to Service Exception*/
			return "011";	
		case 12:
			/*ERROR Code Related to Cache Exception*/
			return "012";
		default:
			return "001";
		}
	}
}