package com.reds.service.cassandraloaderapi.exception;
import com.reds.library.redscommons.exception.AbstractPlatformException;

/**
 * <b>Purpose:</b> Exception class for Cassandraloader
 *
 * @author <b>Algols Builder</b>
 *
 *			This code is generated by Reds
 */
public class CassandraloaderException extends AbstractPlatformException {

	/**
	 * Default serialVersionId
	 */
	private static final long serialVersionUID = 1L;

	public CassandraloaderException(String code) {
		super(code);
	}

	/**
	 * @param code - Error Code
	 * @param message
	 */
	public CassandraloaderException(String code, String message) {
		super(code, message);

	}

	/**
	 * @param code  - Error Code
	 * @param message
	 * @param cause
	 */
	public CassandraloaderException(String code, String message, Throwable cause) {
		super(code, message, cause);

	}

	/**
	 * @param code  - Error Code
	 * @param message
	 * @param cause
	 * @param enableSuppression
	 * @param writableStackTrace
	 */
	public CassandraloaderException(String code, String message, Throwable cause, boolean enableSuppression,
			boolean writableStackTrace) {
		super(code, message, cause, enableSuppression, writableStackTrace);

	}

}
